//UPLOAD IMAGE 
export const ON_IMAGE_UPLOAD_START = 'ON_IMAGE_UPLOAD_START';
export const ON_IMAGE_UPLOAD_SUCCESS = 'ON_IMAGE_UPLOAD_SUCCESS';
export const ON_IMAGE_UPLOAD_FAIL = 'ON_IMAGE_UPLOAD_FAIL';

//GET ALL IMAGES
export const ON_GET_IMAGES_START =   'ON_GET_IMAGES_START';
export const ON_GET_IMAGES_SUCCESS = 'ON_GET_IMAGES_SUCCESS';
export const ON_GET_IMAGES_FAIL =    'ON_GET_IMAGES_FAIL';